### ISSUE TITLE
Erlang

### ISSUE THREAD

**Issue by ShalokShalom** [Shen-Language/wiki#5]
Hi :)

Your homepage speaks about an port to Erlang and I am interested into the details.

Currently, there is no implementation here:
https://github.com/Shen-Language/wiki/wiki

**Comment by rkoeninger** [comment]
Erlang port is here: https://github.com/sborrazas/shen-erl

Added link to it to the wiki home page.

**Comment by rkoeninger** [comment]
Re-open if you have any more questions.

**Comment by ShalokShalom** [comment]
Thanks. All fine :+1:
