### ISSUE TITLE
Error: invalid number of arguments  in `shen.dict-keys` and `shen.dict-values`

### ISSUE THREAD

**Issue by fraya** [Shen-Language/wiki#6]
I have an error using a dictionary that is stored with `set`

    Shen, copyright (C) 2010-2015 Mark Tarver
    www.shenlanguage.org, Shen 22.2
    running under Common Lisp, implementation: SBCL
    port 3.0.2 ported by Mark Tarver, Robert Koeninger and Bruno Deferrari
    exit REPL with (cl.exit)

    (0-) (shen.dict-values (shen.dict 3))
    []

    (1-) (set *test* (shen.dict 3))
    funex19

    (2-) (shen.dict-> (value *test*) foo bar)
    bar

    (3-) (shen.<-dict (value *test*) foo)
    bar

    (4-) (shen.dict-values (value *test*))
    invalid number of arguments: 3

    (5-) (shen.dict-keys (shen.dict 3))
    []

    (6-) (shen.dict-keys (value *test*))
    invalid number of arguments: 3

**Comment by tizoc** [comment]
Oops, I broke this when I added optimizations for dicts in one of the latest releases.

Closing this issue because this is Shen/CL specific, will continue here: https://github.com/Shen-Language/shen-cl/issues/48
